_target_: src.models.HMnist.HMnistModels.HMnistVIB

z_dim: 20

image_preprocessor: null
encoder:
  _target_: src.models.Encoders.DiagonalEncoder
  hidden_sizes: [7840 ,1024, 1024]
  z_dim: 20

decoder:
  _target_: src.models.Decoders.MultinomialDecoder
  hidden_sizes: [20, 10]
  num_sample: 1

num_classes: 10
lr: 1e-3
weight_decay: 0.005
beta: 0.001

